server:
  port: 8070

spring:
  application:
    name: "jpa"
  profiles:
    active: "default"
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: loctran
    password: Loc123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      format-sql: true
    show-sql: false
